name: clashilator
version: 0.1.0
category: hardware

dependencies:
  - base
  - Cabal
  - lens

  - clash-lib
  - clash-ghc
  - regex-applicative
  - text
  - filepath
  - directory
  - stache
  - aeson
  - unordered-containers
  - optparse-applicative
  - shake

source-dirs:
  - src

extra-source-files:
  - template/Makefile.mustache
  - template/Interface.h.mustache
  - template/Impl.cpp.mustache
  - template/Impl.h.mustache
  - template/VerilatorFFI.hsc.mustache

library:
  exposed-modules:
    - Clash.Clashilator
    - Clash.Clashilator.Setup

executables:
  clashilator:
    main: main.hs
