name: clashilator
version: 0.1.0
category: Hardware, Development
synopsis: Automated Clash to Verilator bridge
description:
  Code generator and Setup.hs hooks to generate a Verilator simulation
  and access it from Clash
maintainer: Gergő Érdi <gergo@erdi.hu>
github: gergoerdi/clashilator

dependencies:
  - base
  - Cabal
  - lens

  - clash-lib
  - clash-ghc
  - regex-applicative
  - text
  - filepath
  - directory
  - stache
  - aeson
  - unordered-containers
  - optparse-applicative
  - shake
  - split

source-dirs:
  - src

extra-source-files:
  - template/Makefile.mustache
  - template/Interface.h.mustache
  - template/Impl.cpp.mustache
  - template/Impl.h.mustache
  - template/VerilatorFFI.hsc.mustache

library:
  exposed-modules:
    - Clash.Clashilator
    - Clash.Clashilator.Setup

executables:
  clashilator:
    main: main.hs
