name: clashilator
version: 0.1.0
category: hardware

dependencies:
  - base
  - clash-lib
  - regex-applicative
  - text
  - filepath
  - directory
  - stache
  - aeson
  - unordered-containers
  - optparse-applicative

source-dirs:
  - src

executables:
  clashilator:
    main: main.hs
