name: clashilator
version: 0.1.0
category: hardware

dependencies:
  - base
  - clash-lib
  - regex-applicative
  - text
  - filepath
  - directory
  - stache
  - aeson
  - unordered-containers
  - optparse-applicative
  - shake

source-dirs:
  - src

executables:
  clashilator:
    main: main.hs
    extra-source-files:
      - template/Makefile.mustache
      - template/Interface.h.mustache
      - template/Impl.cpp.mustache
      - template/Impl.h.mustache
      
      - template/Setup.hs.mustache
      - template/package.yaml.mustache
      - template/VerilatorFFI.hsc.mustache
